name: Build

on:
  push:
    branches:
      - main
      - develop
      - feature/*
    paths:
      - ".github/workflows/build.yml"
      - "app/**"
  pull_request:
    branches:
      - main
      - develop
      - feature/*
    paths:
      - ".github/workflows/build.yml"
      - "app/**"
  schedule:
    - cron: "22 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('west.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true

      - name: Initialize workspace (west init)
        run: west init -l app

      - name: Update modules (west update)
        run: west update

      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export

      - name: Build firmware for blue48 left half
        run: west build -d build/left -b nice_nano_v2 -s app -DSHIELD=blue48_left
        env:
          ZEPHYR_BASE: ${{ github.workspace }}/zephyr
          ZMK_CONFIG: ${{ github.workspace }}

      - name: Upload left firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: left_firmware
          path: build/left/zephyr/zmk.uf2

      - name: Build firmware for blue48 right half
        run: west build -d build/right -b nice_nano_v2 -s app -DSHIELD=blue48_right
        env:
          ZEPHYR_BASE: ${{ github.workspace }}/zephyr
          ZMK_CONFIG: ${{ github.workspace }}

      - name: Upload right firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: right_firmware
          path: build/right/zephyr/zmk.uf2
